_wandb:
    value:
        cli_version: 0.21.1
        e:
            eixtfdustji4nk4p3g5m16u1qxpxiggr:
                args:
                    - --local_rank=1
                    - --path_to_json
                    - /home/public/htnguyen/project/ColonGPT/dataset/ColonINST/Json-file-clean/train/ColonINST-train-cap.json
                    - --path_to_image_folder
                    - /home/public/htnguyen/project/ColonGPT/dataset/ColonINST/Positive-images
                    - --pretrained_language_model_path
                    - meta-llama/Llama-3.2-1B-Instruct
                    - --pretrained_vision_encoder_path
                    - google/siglip-so400m-patch14-384
                    - --pretrained_vision_encoder_type
                    - siglip
                    - --vision_projector_type
                    - SPP
                    - --fusion_type
                    - concatenation
                    - --pyramid_shapes
                    - '[[14, 14], [7, 7], [1, 1]]'
                    - --log_every_update_step
                    - "10"
                    - --training_stage
                    - "1"
                    - --train_batch_size_per_device
                    - "16"
                    - --gradient_accumulation_steps
                    - "2"
                    - --num_train_epochs
                    - "20"
                    - --checkpointing_steps
                    - "500"
                    - --output_dir
                    - train_test
                    - --seed
                    - "42"
                    - --optimizer
                    - adamw
                    - --learning_rate
                    - "2e-4"
                    - --lr_scheduler
                    - cosine
                    - --lr_warmup_steps
                    - "500"
                    - --dataloader_num_workers
                    - "2"
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "97568071680"
                        used: "40585502720"
                email: thangnguyen15700@gmail.com
                executable: /home/public/htnguyen/miniconda3/envs/ColonGPT/bin/python3.12
                git:
                    commit: 1da0131e8467594b922eb6293de17d2119c81551
                    remote: https://github.com/wilnn/ColonGPT.git
                gpu: NVIDIA RTX 6000 Ada Generation
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-b0f4f434-b9ca-67c7-e06b-ce89dcc6eb96
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-127d8af0-cc76-8afd-c966-cf3b442dfb3b
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-6b859228-2f24-3cd9-b814-9858feda51ab
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-c6810d34-21a5-b0c3-7b31-85a299e0eca6
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-c4e0de87-ebe0-eee7-12c3-38561568c900
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-b09c2c00-1d99-bc16-6220-cf4324da0b05
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-0ac1cc71-e202-5b8e-72c9-f484105ac331
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-1e6fd998-92a8-2169-b67d-3682628ae2a1
                host: cs-gpu2.cs.uml.edu
                memory:
                    total: "1081792536576"
                os: Linux-6.8.0-79-generic-x86_64-with-glibc2.39
                program: -m src.train.train
                python: CPython 3.12.11
                root: /home/public/htnguyen/project/ColonGPT
                startedAt: "2025-09-16T21:33:13.412384Z"
                writerId: eixtfdustji4nk4p3g5m16u1qxpxiggr
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 98
            "3":
                - 16
            "4": 3.12.11
            "5": 0.21.1
            "6": 4.53.0
            "12": 0.21.1
            "13": linux-x86_64
LM_full_fine_tuning:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
adam_weight_decay:
    value: 0.01
allow_tf32:
    value: false
bf16:
    value:
        enabled: true
checkpointing_steps:
    value: 500
custom_max_length:
    value: null
dataloader_num_workers:
    value: 2
enable_npu_flash_attention:
    value: false
enable_xformers_memory_efficient_attention:
    value: false
fusion_type:
    value: concatenation
gradient_accumulation_steps:
    value: 2
gradient_checkpointing:
    value: false
hub_model_id:
    value: null
hub_token:
    value: null
ignore_index:
    value: -100
image_tag:
    value: <image>
learning_rate:
    value: 0.0002
local_rank:
    value: 1
log_every_update_step:
    value: 10
logging_dir:
    value: logs
lr_scheduler:
    value: cosine
lr_warmup_steps:
    value: 500
max_grad_norm:
    value: 1
max_train_samples:
    value: null
max_train_steps:
    value: 52100
mixed_precision:
    value: null
num_train_epochs:
    value: 20
optimizer:
    value: adamw
output_dir:
    value: train_test
path_to_image_folder:
    value: /home/public/htnguyen/project/ColonGPT/dataset/ColonINST/Positive-images
path_to_json:
    value: /home/public/htnguyen/project/ColonGPT/dataset/ColonINST/Json-file-clean/train/ColonINST-train-cap.json
path_to_val_json:
    value: null
pretrained_language_model_path:
    value: meta-llama/Llama-3.2-1B-Instruct
pretrained_vision_encoder_path:
    value: google/siglip-so400m-patch14-384
pretrained_vision_encoder_type:
    value: siglip
push_to_hub:
    value: false
pyramid_shapes:
    value: '[[14, 14], [7, 7], [1, 1]]'
rank:
    value: 4
report_to:
    value: tensorboard
resume_from_checkpoint:
    value: null
scale_lr:
    value: false
seed:
    value: 42
train_batch_size_per_device:
    value: 16
train_micro_batch_size_per_gpu:
    value: 16
training_stage:
    value: 1
use_8bit_adam:
    value: false
validation_epochs:
    value: 1
vision_projector_type:
    value: SPP
